# Generated by Django 4.2.4 on 2023-08-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0003_alter_room_created_by_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="created_by_name",
            field=models.CharField(max_length=150),
        ),
    ]
