# Generated by Django 4.2.4 on 2023-08-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0004_alter_room_created_by_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
