# Generated by Django 4.2.4 on 2023-08-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0005_alter_room_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="content",
            field=models.TextField(default="content"),
            preserve_default=False,
        ),
    ]
